### ISSUE TITLE
[BUG]: Empty events

### ISSUE THREAD

**Issue by marsanla** [getlago/lago-api#1118]
**Describe the bug**
I installed Lago using docker-compose. After doing several actions to test the application, I checked that the events from the developer section were empty.

```
Looks like there are no events in the Events list.
Start building billable metrics, plans or add-ons to see events here.
```

**To Reproduce**
1. Do some actions
2. Go to developer/events
3. Empty events

**Expected behavior**
We should see events.

**Screenshots**
<img width="1307" alt="Captura de pantalla 2023-06-18 a las 10 24 10" src="https://github.com/getlago/lago-api/assets/1122550/9777a666-0b22-40f4-b430-bdb1f67d3c58">
<img width="1297" alt="Captura de pantalla 2023-06-18 a las 10 24 19" src="https://github.com/getlago/lago-api/assets/1122550/20d90e5f-832e-4b95-853c-4f81f548f22f">

**Version**
- Lago: v0.37.0-beta

**Comment by vincent-pochet** [comment]
Hello @marsanla,

Thank you for reaching out

Here are few thinks you chould check:
- Make sure the worker container is up (`docker-compose ps`)
- Check the logs from the api container (`docker-compose logs api`) to make sure the event you sent were well received
- Check the logs from the worker container (`docker-compose logs api-worker`) to make sure that nothing happen during the processing of the events

**Comment by jdenquin** [comment]
@marsanla any updates?

**Comment by jdenquin** [comment]
we will close this issue this week since we do not have more informations @marsanla

**Comment by marsanla** [comment]
I'm sorry for not getting back to you sooner. Because of these issues, I stopped trying Lago. I tried it again today, but I still need help with the same issue. I checked the events table in postgress, and it is empty. It looks like it doesn't store anything. What could be the problem? Is there any missing env variable?

I ran the default installation in docker and followed the Readme md.

**Comment by jdenquin** [comment]
@marsanla you should check if your `api-worker` is running in Docker, if everything is fine but you can't see any event ingested, it can be the issue

**Comment by geekyayush** [comment]
facing the same issue.
I created a billable metric, a plan, and a customer but the developer events list is still empty.
Everything shows green on the docker container side.

**Comment by jdenquin** [comment]
@geekyayush 
Can you activate the `LAGO_SIDEKIQ_WEB=true` in the `docker-compose.yml` file, restart the `api` container and go on `your_api_url/sidekiq` to check errors?

**Comment by marsanla** [comment]
I fixed just changing the ENV variable:

`SIDEKIQ_EVENTS=true`
