### ISSUE TITLE
[BUG]: invoice PDF generation API doesn't work (only works with graphql)

### ISSUE THREAD

**Issue by gabrielseibel1** [getlago/lago-api#1198]
**Describe the bug**
I'm trying to generate invoices PDFs. The UI does it by using a graphql mutation, and it works, generating valid PDF files (although it does not seem to trigger the invoice.generated webhook event).
_The problem is:_
If you try to POST to the HTTP API documented [here](https://doc.getlago.com/api-reference/invoices/download) (cURL, postman, golang client) it doesn't work, generating an invalid PDF.

**To Reproduce**
1. Create a one-off invoice I1
2. Download it via the UI (works)
3. Generate a one-off invoice I2
4. Download it via graphql call on postman (works)
3. Generate a one-off invoice I3
4. Download it via POST as per info [here](https://doc.getlago.com/api-reference/invoices/download)
5. Have no response
6. Try to download it via the UI (fails)
7. Try to download it by going to the "file_url" provided in the invoices API response (fails)

**Expected behavior**
Downloading invoices PDFs from HTTP API should generate valid PDFs and trigger the invoice.generated webhook event with a valid "file_url" field.

**Screenshots**
![image](https://github.com/getlago/lago-api/assets/23637113/ca8cb78d-2a42-44d3-8df3-f57740c3c5b0)

**Version**
- Lago: v0.40.0-beta (also tried v0.32.0-beta, so probably all versions?)

**Comment by jdenquin** [comment]
Hello @gabrielseibel1 

How is your API configured? do you use local storage or S3?

**Comment by gabrielseibel1** [comment]
I'm using a similar approach to deploying lago as the one you have documented for docker compose, but i'm using the a modified helm chart of yours.

**Comment by jdenquin** [comment]
okay this should not be an issue.
What is your `LAGO_API_URL` env var for the `api` ?

**Comment by gabrielseibel1** [comment]
@jdenquin There is an ingress resource for lago-api service and the LAGO_API_URL is set to that host. I don't think that's the problem as well, because generating the PDF from the UI (using graphql) works, but not on the regular http api (generates URL in the same pattern, but it seems the generated file is not a valid pdf?)

**Comment by jdenquin** [comment]
the api uses the exact same generation code, just one difference : it's asynchronous and you receive a webhook when it's ready.
The generation on the FE side is synchronous.

**Comment by gabrielseibel1** [comment]
Yes, but the URL generated by the api call (in the received webhook for example) points to somewhere that shows the error "failed to load pdf document". And the webhook is not the problem, because the api that fetches the invoice also retrieves an invalid PDF URL in the file_url field. Are you able to generate pdfs async with the api on your side?

**Comment by jdenquin** [comment]
yes it works fine on our side, can you try to update to the last lago version?
