### ISSUE TITLE
[FEAT]: Configurable Stripe checkout success_url

### ISSUE THREAD

**Issue by carl-shen** [getlago/lago-api#1274]
**Is your feature request related to a problem? Please describe.**

The `checkout_url` for a Stripe session returned by the `"customer.checkout_url_generated"` webhook takes a user to getlago.com after a successful request. This is the `success_url` field when generating a Stripe session, and it appears to be hard-coded in the following line:

`CHECKOUT_SUCCESS_URL = 'https://www.getlago.com'`
https://github.com/getlago/lago-api/blob/main/app/services/payment_provider_customers/stripe_service.rb#L5

This interrupts our desired customer sign-up process.

**Describe the solution you'd like**

We would like the `CHECKOUT_SUCCESS_URL` to be configurable if possible, perhaps as an environment variable that can be configured in `docker-compose.yml`.

**Describe alternatives you've considered**

We could potentially generate a Stripe checkout session with our own logic, by it would be easier to make use of the logic Lago provides if we could make it work.

**Additional context**

None

**Comment by mathieu-lago** [comment]
Hi @carl-shen - thanks for reaching out! This feature is on our radar, although it hasn't been prioritised yet.

May I ask you to [add your vote](https://getlago.canny.io/developer-experience/p/edit-success-checkout-url-stripe) to this ticket, so that we can keep you informed about our progress?
