### ISSUE TITLE
[BUG]: Download invoice via link on API response works on second try

### ISSUE THREAD

**Issue by drejc** [getlago/lago-api#1297]
**Describe the bug**
We perform following API call (no invoice has been generated / no file_url is available when listing invoices)

POST /api/v1/invoices/{lago_id}/download
we get a 200 response that is empty

After repeating the same call we get a response with a file_url populated.

**To Reproduce**
1. Create an invoice
2. Get invoice file_url via download invoice API call POST /api/v1/invoices/{lago_id}/download
3. 200 response - no content is returned
4. Retry get invoice file_url via download invoice API call POST /api/v1/invoices/{lago_id}/download
5. 200 response - JSON with populated invoice_url is returned

**Expected behavior**
After first call either error should be returned on 200 with content.

**Screenshots**

**Additional context**

**Version**
- Lago: [v0.45.0-beta](https://github.com/getlago/lago-api/tree/v0.45.0-beta)

**Comment by jdenquin** [comment]
@drejc 

It is actually logic, the first call generate the PDF file, it sends you a wedhook when it's ready, the second call, since the PDF was already generated, returns it

**Comment by drejc** [comment]
The expected behaviour (in my eyes) is to GET a invoice - not to start the invoice creation. 
If this is a call to "create" a PDF invoice I would expect a PUT or PATCH request not a GET request as the resource in this case is not available.

**Comment by jdenquin** [comment]
I see your point.
I'm not sure we'll update this behavior for now since it can be a breaking change to remove the `GET` endpoint

**Comment by drejc** [comment]
Rather then removing the GET I would introduce a PUT - so the end user knows when he is creating an invoice and when he is getting an invoice. This are two separate actions. 
Just my two cents ;)

**Comment by jdenquin** [comment]
I'm logging it to our improvements list, thanks for it!

**Comment by jdenquin** [comment]
https://getlago.canny.io/developer-experience/p/use-a-put-endpoint-to-generate-invoice-pdf
