### ISSUE TITLE
[BUG]: Lago API endpoint for creation of billable-metric fails

### ISSUE THREAD

**Issue by seandlg** [getlago/lago-api#1356]
**Describe the bug**
When using the `REST`-API to create a `billable-metric`, this fails.

**To Reproduce**

1. `git clone https://github.com/getlago/lago.git`
2. `cd lago`
3. `echo "LAGO_RSA_PRIVATE_KEY=\"$(openssl genrsa 2048 | base64)\"" >> .env && source .env`
4. `docker-compose up`
5. Use `curl` to issue request

```bash
curl -H 'Authorization: Bearer YOUR-API-KEY' -d '{
  "billable_metric": {
    "name": "Storage",
    "code": "storage",
    "description": "GB of storage used in my application",
    "recurring": false,
    "field_name": "gb",
    "aggregation_type": "sum_agg",
    "group": {
      "key": "region",
      "values": [
        "us-east-1",
        "us-east-2",
        "eu-west-1"
      ]
    }
  }
}' 'http://localhost:3000/api/v1/billable_metrics'
```

**Expected behavior**
The billable metric gets created. Instead, I receive a `400`:

```txt
{
  "status": 400,
  "error": "BadRequest: param is missing or the value is empty: billable_metric"
}
```

Which suggests adding a param:

```bash
curl -H 'Authorization: Bearer YOUR-API-KEY' -d '{
  "billable_metric": {
    "name": "Storage",
    "code": "storage",
    "description": "GB of storage used in my application",
    "recurring": false,
    "field_name": "gb",
    "aggregation_type": "sum_agg",
    "group": {
      "key": "region",
      "values": [
        "us-east-1",
        "us-east-2",
        "eu-west-1"
      ]
    }
  }
}' 'http://localhost:3000/api/v1/billable_metrics?billable_metric=why-tho'
```

which crashes the server:

```txt
{
  "status": 500,
  "error": "Internal Server Error"
}
```

**Additional context**
The frontend uses some Graphql RPC magic.

**Version**
- [Lago version](https://github.com/getlago/lago/tree/2747b04ea90c8b87c0413f07bda117547176a52f)

**Comment by mathieu-lago** [comment]
Hi @seandlg - thanks for reaching out. I've downloaded the latest version and successfully created a billable metric with the same attributes via API.

Did you add the header `'Content-Type: application/json'` as indicated in [the documentation](https://docs.getlago.com/api-reference/billable-metrics/create)?

**Comment by seandlg** [comment]
Indeed, it was the missing `Content-Type: application/json` header. Thank you :-)
