### ISSUE TITLE
[FEAT]: Swedish Translation for Lago

### ISSUE THREAD

**Issue by emilioarvidisaksson** [getlago/lago-api#1364]
**Describe the solution you'd like**
I've translated the necessary text and date formats into Swedish, with attention to detail on cultural and language-specific intricacies such as capitalization and abbreviation. Please find the translations in this gist: [Swedish Translation for Lago](https://gist.github.com/emilioarvidisaksson/8c312a88e86094b1027e12792b401292)

**Additional context**
While translating, I encountered some nuances that might require further attention:

1. Capitalization of Months/Days: I was unsure how the code handles capitalization for date formats. In your examples, month and day names are capitalized, but in Swedish, they usually follow sentence capitalization rules. I've kept them in lowercase, but they should be capitalized when starting a sentence.
2. Abbreviation and Punctuation: I added a "." after the months and days when I shortened the names, except for those with 4 letters or less, as they are generally not abbreviated in Swedish.
3. Date Format Concern: The date format (3.2) in your example included a dot, and I followed suit. However, this could potentially result in two dots in the final display depending on the implementation. I chose to include the dot in abbr_month_names to clearly indicate which ones are abbreviated.

**Comment by michaelponrajah** [comment]
Hello @emilioarvidisaksson 👋 

Thanks for the contribution, I'll keep you posted once the language is added!
