### ISSUE TITLE
[BUG]: Subscriptions status filter is ignored

### ISSUE THREAD

**Issue by FaustoJohn** [getlago/lago-api#1392]
**Describe the bug**
The status filter for the Subscriptions query is ignored when provided

**To Reproduce**
- Run below request (change host accordingly)
``` curl
curl --location --globoff '<host>/api/v1/subscriptions?page=1&per_page=2&status=[%22terminated%22]' \
--header 'Authorization: Bearer <api-key>'
```

**Expected behavior**
The expected behaviour is for the returned list of subscriptions to be filtered by the provided set of statuses and if no matching subscriptions are found then an empty list should be returned

**Screenshots**
![image](https://github.com/getlago/lago-api/assets/3326738/aa997ad3-76f5-49b4-9698-ac437cd8611f)

**Additional context**

**Version**
- Lago: v0.49.0-beta

**Comment by mathieu-lago** [comment]
Please try with `/api/v1/subscriptions?page=1&per_page=2&status[]=terminated`.
