### ISSUE TITLE
:lady_beetle:  Amount cents field should be handled as BigInt, not Integer

### ISSUE THREAD

**Issue by vincent-pochet** [getlago/lago-api#180]
All amount fields are stored as `bigint` in the database. This is the recommended behaviors when dealing with amounts.

The bug is that those fields are exposed and ingested in GraphQL as `Integer`.  It will lead to an error if an amount_cents fields contains a value higher than `2.147.483.647`
It will probably be an edge case for most amount fields, but it could happen on fields like invoice amount. 

The proper way to fix it would to expose all amount fields has `BigInt`

**Comment by jerbob92** [comment]
I think GraphQL does not have a BigInt/int64 type.

[GraphQL says the following](http://spec.graphql.org/June2018/#sec-Int):

> Numeric integer values larger than 32‐bit should either use String or a custom‐defined Scalar type, as not all platforms and transports support encoding integer numbers larger than 32‐bit.

In a project that I worked on we did the following for amounts in GraphQL:

- Provide the GraphQL type `Amount`
- In that Amount type: create a resolver to allow getting the amount in string
- In that Amount type: create a resolver to allow getting the amount in float
- In that Amount type: create a resolver to allow getting the amount split in units and cents (this doesn't give you a whole lot of extra room though)
- In that Amount type: create a resolver to allow getting the amount split up in 2 Integer parts (part 1 and part 2) and combine them on the other side again by doing `int64(first) + (int64(second) << 32)`

**Comment by vincent-pochet** [comment]
Thank you @jerbob92 for your comment.

Indeed GraphQL does not have such type, but since the project is using [GraphQL ruby](https://graphql-ruby.org/), I was thinking at using the built-in BigInt type implementation (see: https://graphql-ruby.org/api-doc/2.0.11/GraphQL/Types/BigInt)

It stills require the front-end to handle it properly.

**Comment by jerbob92** [comment]
Ah I think that would work yes, that's basically just passing it as a string.
