### ISSUE TITLE
[BUG]: estimate fees API create an entry in database.

### ISSUE THREAD

**Issue by ccfiel** [getlago/lago-api#1812]
**Describe the bug**
Calling estimate fees API https://docs.getlago.com/api-reference/events/estimated-fee will create an event entry in the database. The expected flow gives the estimated fee based on the event parameter and it should not create a database entry.

**To Reproduce**

See the video to reproduce the behavior

https://github.com/getlago/lago-api/assets/1788360/f137a155-3d3d-40f0-913c-5c3585b17785

**Expected behavior**
After calling the estimate fees API it should NOT create a database entry.

**Version**
- Lago: v1.0.0
-

**Comment by vincent-pochet** [comment]
Thank you for reporting this @ccfiel 
The fix have been merged into main, it will be part of the next release.
