### ISSUE TITLE
[BUG]: Downloading invoice throgh Rest API not working

### ISSUE THREAD

**Issue by abbasatayee** [getlago/lago-api#1829]
**Describe the bug**

**To Reproduce**
1. Download an invoice using javascript client and it gives you a file_url that does not work (but if you try to download the pdf using Graphql API from front-end it works)
2. click on the file url (it sends Document not found) 

**Expected behavior**
it should be able to download the file using rest api

**Screenshots**
![image](https://github.com/getlago/lago-api/assets/49268657/dbf8480e-b1f9-4e5a-8976-7486c3be9cba)

**Version**
- Lago: v1.0.0

**Comment by jdenquin** [comment]
URL is the same on both api and GraphQL side, has your javascript environment access to API?

**Comment by abbasatayee** [comment]
> URL is the same on both api and GraphQL side, has your javascript environment access to API?

yes it has access to javascript environment. I have checked both URL's looks same but whenever I get file_url using rest api its not working and with the dashboard one that is using graphql api working perfectly.

**Comment by jdenquin** [comment]
how do you download the file with the `api`? if it works with the UI, it should work with the api too, it's basically the same file
