### ISSUE TITLE
[BUG]: Changing plan from an annual plan to monthly plan is treated as an upgrade

### ISSUE THREAD

**Issue by ccfiel** [getlago/lago-api#1834]
**Describe the bug**
When changing the plan from an annual to a monthly one, it will be treated as an upgrade, not a downgrade. So, it will terminate the old plan and retain the new one, which it should not. See this line: https://github.com/getlago/lago-api/blob/main/app/services/subscriptions/create_service.rb#L86

**To Reproduce**
Please view the video to reproduce the bug: https://github.com/getlago/lago-api/assets/1788360/e5aff75c-12f4-4f67-8cb1-9d9ac1ade849

**Expected behavior**
It should retain the annual plan as active and then the monthly plan pending until the yearly plan ends.

**Version**
- Lago: v1.1.0

**Comment by mathieu-lago** [comment]
Hi @ccfiel - this is actually the expected behaviour.

The system automatically determines whether the change of plan is an upgrade or a downgrade based on the daily value of each plan:

- Monthly plan: $17 / 30 days = $0.57
- Yearly plan: $134 / 365 days = $0.37

As $0.57 > $0.37, this change is considered as an upgrade.

https://docs.getlago.com/guide/subscriptions/upgrades-downgrades#upgrades-behavior

**Comment by ccfiel** [comment]
@mathieu-lago When changing from annual to monthly, it is considered an upgrade. I don't think it makes sense. Would you agree?

**Comment by ccfiel** [comment]
"Hi @mathieu-lago, I was thinking that it might be helpful to add an optional parameter when creating a subscription. This parameter could be upgraded or downgraded later on if it's not initially supplied, and would follow the default logic. What do you think? If you agree, I'd be happy to submit a pull request."

**Comment by mathieu-lago** [comment]
Copying here the answer I gave you on Slack, in case other people are interested:

This improvement is on our radar but hasn’t been prioritised yet:

- https://getlago.canny.io/feature-requests/p/allow-delayed-upgrades
- https://getlago.canny.io/feature-requests/p/instantly-downgrade-from-monthly-to-annual-plans

> "I thought it might be helpful to add an optional parameter when creating a subscription. This parameter could be upgraded or downgraded later on if it’s not initially supplied and would follow the default logic. What do you think?"

Contributions are always welcome! There may be some edge cases or backend logic to take into consideration, but our team will be able to check this when reviewing your PR.
