### ISSUE TITLE
[BUG]: Segmentation fault after running `rake db:migrate`

### ISSUE THREAD

**Issue by ghun131** [getlago/lago-api#1894]
**Describe the bug**
I follow the instruction here https://github.com/getlago/lago-api/wiki to setup lago-api at local. Until I reach the part `rake db:migrate`, I encountered the error message `Segmentation fault:...`. But still if I run `rails s`, the server still works

**To Reproduce**
1. Follow instruction here to install at your local https://github.com/getlago/lago-api/wiki
3. After running `rake db:setup`, run `rake db:migrate`

**Expected behavior**
`rake db:migrate` finishes migration without error

**Screenshots**
![image](https://github.com/getlago/lago-api/assets/33661599/0ba48b0c-a30a-4975-8b3f-5333198cd57e)

**Additional context**
I'm using MacBook Pro M1 2020

**Version**
- Lago: v1.1.2

**Comment by ghun131** [comment]
This is the content of crash report https://gist.github.com/ghun131/faeb26c676c5b6c3dd64dbdf8f987234

**Comment by jdenquin** [comment]
@ghun131 can you try a `rake db:migrate:primary` ?

**Comment by ghun131** [comment]
> @ghun131 can you try a `rake db:migrate:primary` ?

I ran the command and same error appeared. Should I remove my local repo and reinstall every before running the command?

**Comment by ghun131** [comment]
After reinstalling, I got the same error. I thought maybe because I didn't use `docker-compose up db` like what it said in the Wiki so I tried that but this error came up
![image](https://github.com/getlago/lago-api/assets/33661599/48c532bb-fb36-4f2c-9dd6-5210adb76eb1)

**Comment by jdenquin** [comment]
Ho sorry, this wiki is outdated and we do not support it anymore, you should follow this one : https://github.com/getlago/lago/wiki/Development-Environment if you want to setup a proper dev environment

**Comment by ghun131** [comment]
> Ho sorry, this wiki is outdated and we do not support it anymore, you should follow this one : https://github.com/getlago/lago/wiki/Development-Environment if you want to setup a proper dev environment

I followed the instruction and when I accessed https://app.lago.dev/, there is this error
<img width="1235" alt="image" src="https://github.com/getlago/lago-api/assets/33661599/05a0196e-881a-47ca-b4d5-2ded619f091b">

My docker version is 20.10.12 and docker-compose is 1.29.2. It's a Mac Pro M1 2020

**Comment by ghun131** [comment]
> can you check if traefik is running (you can access it on traefik.lago.dev)

Thank you for your reply but this way of setting up is too much for me. Maybe I'll do it at another time

**Comment by jdenquin** [comment]
the dev environment can be tricky but it should run very fine by following the wiki, I close this one, open a new Issue if you need help!
