### ISSUE TITLE
[FEAT]: Karafka 2.4.0 + WaterDrop Breaking Changes

### ISSUE THREAD

**Issue by mensfeld** [getlago/lago-api#1966]
**Is your feature request related to a problem? Please describe.**

Hey :wave: . I'm Maciej. Karafka author. I just wanted to give you a heads-up that Karafka 2.4 contains some breaking changes. There is no immediate need of upgrade as there are no bigger issues that were fixed but not backported, though at some point you may want to consider an upgrade.

https://karafka.io/docs/Upgrades-2.4/

**Describe the solution you'd like**

The solution in a long term would be to upgrade :)

**Describe alternatives you've considered**

Not upgrading and being sad.

**Additional context**

https://karafka.io/docs/Upgrades-2.4/
https://mensfeld.pl/2024/04/karafka-2-4-release-announcement-advancing-kafka-processing-for-ruby-and-rails/

**Comment by jdenquin** [comment]
thanks @mensfeld, since we don't use karafka in production right now I'll do the update

**Comment by mensfeld** [comment]
Please be mindful of waterdrop changes as well. While all of the settings I changed are changed "for better" it is better to be aware :)

Since you are now aware I will consider this resolved.
