### ISSUE TITLE
[BUG]: clock did not work with gcp cloudrun

### ISSUE THREAD

**Issue by superpoussin22** [getlago/lago-api#2036]
**Describe the bug**
using GCP cloud run , the cloud run need an endpoitn to do a startup check to ensure the container is running 
but the clock container start ./scripts/start.clock.sh and didn't provide an endpoint like an open port. (ex: 3000 ) to ensure the service is up 

**Expected behavior**
have an endpoint to check the service is up and running 

**Screenshots**

**Additional context**

**Version**
- Lago: v1.3.0 (last version )

**Comment by jdenquin** [comment]
Hello @superpoussin22 (nice nickname!)

Clock service is not running any web server, it's a job process, we can't monitor it like a web server.
Is it possible to launch it as a job or worker on GCP?

**Comment by superpoussin22** [comment]
Hi @jdenquin ,
thanks.
The idea was to use fully managed service ( Cloud run) what require to have something to verify that the service/container start well , this is mandatory in GCP if using serverless and can be done uisng http or tcp or grpc call .

If not doable, it will require then to create a small VM ( same issue I think for the worker part ) 

https://cloud.google.com/run/docs/configuring/healthchecks?hl=en

**Comment by superpoussin22** [comment]
also creating VM will require to give access to the bucket for storage, what will expose the GCS json key what is bad in term of security

**Comment by vincent-pochet** [comment]
Both worker (sidekiqs) and clock (clockwork) services are background process and does run any web server or do not listen to any port. 

The worker health can be monitored using sidekiqmon (see: https://github.com/getlago/lago/blob/main/docker-compose.yml#L140) but it is done by running a command inside the container instance

For the clock part, we are in the process to migrate from clockwork to sidekiq-scheduler, the monitoring aspect will be handled in a similar way.

I'm closing the issue as we have no plan to handle http/tcp or grpc liveness on this services for now, but we are open to contributions
