### ISSUE TITLE
[FEAT]: Add support for Bitcoin as currency

### ISSUE THREAD

**Issue by bumi** [getlago/lago-api#2208]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to define prices in other currencies that the fixed list. Even though this is a ISO list it would be great to be able to charge users in Bitcoin (sats).

**Describe the solution you'd like**
Add Bitcoin to the list of supported languages. It can be added denominated in stats (the smallest unit in Bitcoin) which is commonly used. It would have zero decimal points and we can just use the current formatting settings.

**Describe alternatives you've considered**
Make the list dynamic and allow users to configure their own additional languages. But this would probably require some bigger change as the currencies are currently managed in the constant.

**Additional context**

I am happy to make a PR if you can point me to where to add it. 

As by [this comment](https://github.com/getlago/lago-front/issues/1560#issuecomment-2188186063) the list of currencies is maintained [here](https://github.com/getlago/lago-api/blob/main/app/models/concerns/currencies.rb#L6) 
but I have also seen there is a formatting configuration options: [here](https://github.com/getlago/lago-front/blob/7e77731dbe39cb2e75cecef8b6ed5180105eb99f/src/core/serializers/serializeAmount.ts)

**Comment by bumi** [comment]
I've tried to add the currency, but I don't fully understand why I get different formattings on the invoice:
![CleanShot 2024-06-27 at 07 38 47@2x](https://github.com/getlago/lago-api/assets/318/0cf654e4-3ab3-44ba-996b-7940f5065f8e)

**Comment by jdenquin** [comment]
I assume we talked about it on our slack community also @bumi, whats the decision you made?

**Comment by jdenquin** [comment]
We keep this under our rader cc @michaelponrajah .
But since this currency is not supported by the PSP we integrate with, this is not something we'll develop soon.

I close this issue but feel free to comment if needed!

**Comment by michaelponrajah** [comment]
Please considered this under [our radar](https://getlago.canny.io/feature-requests/p/support-crypto-payments-via-stripe) but not prio for now. We'll definitely get back to you if we open this topic 🙌
