### ISSUE TITLE
[BUG]: challenges encountered when setting up a production install

### ISSUE THREAD

**Issue by prognostikos** [getlago/lago-api#296]
I've been setting up Lago today on our production cluster and have run into two issues:

- Rails will not boot due to a missing/incorrect `RAILS_MASTER_KEY` value. Renaming the encrypted credentials file with `mv config/credentials.yml.enc config/credentials.yml.enc.disabled` solved the issue. I'm not sure why I don't see this in development mode as I think it should try to be decrypted there as well but it only hit me in production.
- Lago is looking for `RSA_PRIVATE_KEY` in the environment instead of `LAGO_RSA_PRIVATE_KEY` as documented [here](https://doc.getlago.com/docs/guide/self-hosting/docker#environment-variables). In development it looks for a file containing the key so that explains why the error only happens in production.

**Comment by jdenquin** [comment]
we do not use encrypted credentials due to the open source scope yes, but this is still present from the legacy repo generation.
We will remove it since it's not used and can cause some errors on a `staging` or `production` environment!

Good catch for the `LAGO_RSA_PRIVATE_KEY`
