### ISSUE TITLE
[BUG]: email address should be unique per customer

### ISSUE THREAD

**Issue by c-nv-s** [getlago/lago-api#374]
Describe the bug
when creating customers with the api it is currently possible to have different ids but all with the same email address.
Is this intentional? Because it would seem to make sense that each customer should have a unique primary email address.

**Comment by michaelponrajah** [comment]
Hello @c-nv-s 👋 
Thanks for asking, actually it would make sense if one customer is equal to one organisation entity but we decided to allow customers sharing the same email address to cover the case of subsidiary company. 

e.g. 
Acme Inc Europe (id: 001 / email: billing@acme.inc) 
Acme Inc Asia (id: 002 / email: billing@acme.inc)

From what we understood it's not a blocker to use the product but feel free to tell us if it's!

**Comment by c-nv-s** [comment]
That's fine
