### ISSUE TITLE
Launch without docker

### ISSUE THREAD

**Issue by oxoWrk** [getlago/lago-api#471]
How can I launch your product without using docker?
I have installed gems and am trying to perform database migration but I get errors.
```
rake aborted!
ArgumentError: Write key must be initialized
```

**Comment by jdenquin** [comment]
Hello there,

You can but it's not recommended.
You have to add all environment variables on your machine, that are defined in the [`docker-compose.yml` file ](https://github.com/getlago/lago/blob/main/docker-compose.yml#L31).

**Comment by jdenquin** [comment]
@oxoWrk did you managed to make it work ?

**Comment by oxoWrk** [comment]
no
`LoadError: cannot load such file -- sprockets/railtie`

**Comment by oxoWrk** [comment]
I made it work.
All migrations were applied without errors.
But when I open the customers section I get the error. 
In  API responses I found this:
`Field 'customerId' doesn't exist on type 'Customer'"`
