### ISSUE TITLE
[BUG]:  create new customer billing configuration 

### ISSUE THREAD

**Issue by shaunie2fly** [getlago/lago-api#501]
Hi,

I'm not sure if this is intentional or not, but when creating a customer if the _billing_provider object_ only contains the _provider_customer_id_  the value is not added  to the item and is returned as null.

submitted customer creation object example :

 ```json
{
        "external_id": "6fb02857-a71e-4ea2-bcf9-57d3a41bd7ba",
        "address_line1": "5230 Penfield Ave",
        "address_line2": null,
        "city": "Woodland Hills",
        "country": "US",
        "email": "dinesh@piedpiper.test",
        "legal_name": "Coleman-Blair",
        "legal_number": "49-008-2965",
        "logo_url": "http://hooli.com/logo.png",
        "name": "brett botsis",
        "phone": "1-171-883-3711 x245",
        "state": "CA",
        "url": "http://hooli.com",
        "vat_rate": 12.5,
        "zipcode": "91364",
        "billing_configuration": {
          "provider_customer_id": "cus_12345",
        }
```

**Comment by jdenquin** [comment]
Hello @shaunie2fly 

the `payment_provider` field is required if you want to add the `provider_customer_id`, if it's not specified it will not save it.
We'll update the doc regarding this behaviour!

**Comment by jdenquin** [comment]
I just updated the doc to precise that this field is required when using the `provider_customer_id` !
