### ISSUE TITLE
[BUG]: cents value used as-is in the invoice

### ISSUE THREAD

**Issue by okoriko** [getlago/lago-api#643]
**Describe the bug**
After generating an invoice in JPY, the cents value seems to be used as-is. It leads to amounts 100 times bigger than they are.
This seems to be happening two places:
1. in the invoice's subtotal
2. in all the values of the PDF version

**To Reproduce**
1. Create a plan with the current in JPY and with a monthly price of 10,000 yen (about 70 USD)
2. Create a customer subscription
3. Terminate it to generate an invoice with pro-rated values
4. Open the invoice and its PDF 

**Expected behavior**
In the screenshot below, the invoice subtotal value should be ¥1,935 instead of ¥193,548. 
In the generated PDF, all values should match the invoice page; the values should be 100 times less.

**Screenshots**
1. subtotal value in the invoice page:
![image](https://user-images.githubusercontent.com/5242874/205310123-b185d64d-32aa-494b-bd64-5d23a781a613.png)
2. generated PDF:
![image](https://user-images.githubusercontent.com/5242874/205310425-e6fbf4da-7a3b-401d-9b24-a3a9b594cd30.png)

**Additional context**
-

**Version**
- Lago: v0.16.1-alpha

**Comment by mathieu-lago** [comment]
Hi @okoriko - thanks for opening this ticket. Our team is currently looking into this issue, and we will get back to you with an update.

**Comment by jdenquin** [comment]
Hello @okoriko, this has been fixed on our side, it will be released in the next version for the OSS!
