### ISSUE TITLE
[IMP]: missing health check when running lago-api as worker

### ISSUE THREAD

**Issue by mpawlowski** [getlago/lago-api#853]
When running the lago-api docker container as a worker with `./scripts/start.worker.sh`, a health endpoint seems to be missing. A health endpoint exists when running the container with `./scripts/start.sh` under `$API_HOST:$API_PORT/health`, but returns a 404 when running as a worker.

**To Reproduce**
1. Deploy `lago-api` using `./scripts/start.worker.sh` and attempt to hit a health endpoint.

**Expected behavior**
I expect a health endpoint to exist so the application can be monitored.

**Context**
A health endpoint is useful for cloud native environments such as Kubernetes where a readinessProbe can be configured to manage the application lifecycle.

**Version**
- Lago: v0.22.1-beta

**Comment by jdenquin** [comment]
The `worker` is not running a web server, thats why you can't see the health endpoint, the `clock` has also the same behavior.
We'll dig into adding a liveness/readiness for both `clock` and `worker` !
