### ISSUE TITLE
[FEAT]: Smaller plan intervals

### ISSUE THREAD

**Issue by BirknerAlex** [getlago/lago-api#865]
**Describe the solution you'd like**
Currently if you create plans via the API it supports following intervals `yearly`, `monthly` or `weekly`. If would be great to also use smaller intervals like `hourly`. 

**Additional context**
We would like to bill customers for hourly rented resources, like AWS or GCP does. So on the end customers should receive one bill per month (end of the month) including all rented compute resources in that month. 

Currently we are solving this task with custom code which is a "nightmare" - which you guys trying to prevent. I can imaging to help contributing to this PR but currently I can't even tell if this is a large change on your side or not. 🤔

**Comment by mathieu-lago** [comment]
Hi @BirknerAlex - the plan interval determines the frequency at which invoices are automatically generated. Therefore, if you want your customers to receive an invoice at the end of each month, you should select the monthly interval.

The usage-based charges in the invoice depend on the [events ingested](https://doc.getlago.com/docs/api/events/metered-event) during the billing period (i.e. during the month) and the [aggregation type](https://doc.getlago.com/docs/guide/billable-metrics/aggregation-types) you selected for your billable metrics.

For example, if you want to charge your customers for compute resources, you can create a billable metric based on the `sum` aggregation type and a custom property (e.g. `vCPU hour`). This billable metric can then be added as a charge to your [plan](https://doc.getlago.com/docs/guide/plans/overview). When the [customer's subscription](https://doc.getlago.com/docs/guide/plans/subscription) starts, you can then start sending events with the number of vCPU hours they consumed (e.g. hourly events or daily events). At the end of the billing period, Lago will automatically calculate the corresponding charge for each customer.

Hope this helps. Please let me know if you have any other questions.

**Comment by BirknerAlex** [comment]
@mathieu-lago - I did take a look to the plan and billable metric documentations, setup lago on our k8s dev cluster and started playing around with it today.

Thanks, it looks it might fit our requirements already except not being able to update the plans prices when the plan is subscribed by some account already. I would love to have some feedback help, I will join in your Slack tomorrow, I think that's a better place than a Github issue, closing now.

Thank you!

**Comment by zumm** [comment]
@mathieu-lago Hi there. Sorry for mention in closed issue, but my case is related to requisted feature. We need half-year interval. Our setup is very simple, but i don't see ways to achive it. We offer two plans for same service: 1 year and half year subcribtion. Difference is only in price, 1 year is cheaper.  Customer pays whole price in advance. No need in invoices or pro ratas.

Could you please help to find "proper" way to achive it?
